org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.244
neo_version_range=[21,)
loader_version_range=[4,)
parchment_minecraft_version=1.21.11
parchment_mappings_version=2025.12.20
mod_id=me_building_gadgets
mod_name=ME Building Gadgets
mod_license=LGPL-3.0
mod_version=21.1.2
mod_group_id=org.chatterjay
mod_authors=Chatterjay
mod_description=Integrates Building Gadgets with the AE network: bind to the network to build directly from ME storage, and automatically submit pattern crafting tasks via a wireless terminal when materials run short creating seamless synergy between building and automated manufacturing.
